### ISSUE TITLE
出一个模块功能简介吧，方便理解

### ISSUE THREAD

**Issue by dapeng17951** [iioter/iotgateway#1]
1.出一个模块功能简介吧，方便理解；
2.代码记得注释哦；
3.架构图呀；

**Comment by Davidzhu001** [comment]
+1

**Comment by iioter** [comment]
hi，我们从驱动开发实操开始，请访问：[驱动开发实操](http://iotgateway.net/docs/iotgateway/driver/drvier)

**Comment by iioter** [comment]
[项目文档官网](http://iotgateway.net/docs/intro)
