### ISSUE TITLE
变化上传改进

### ISSUE THREAD

**Issue by Xuquansheng** [iioter/iotgateway#13]
你好！我们是一家开源erp软件实施商，项目上有IIoT的需求，很高兴有你开源这么一款非常出色的IIot工业物联网网关，我在测试变化上传时遇到了一个问题，就是value不变化时，不上传，这是对的，但是它构成的多级json报文是上传的，这个也应该不上传，对吧？
以下为我的测试数据：
b'{"Modbus-Copy1":[{"ts":1655170338376,"devicestatus":0,"values":{"outQty":500}}]}'
b'{"Modbus-Copy1":[{"ts":1655170343380,"devicestatus":0,"values":{"outQty":500}}]}'
b'{"device":"Modbus-Copy1","id":"44743e54-9f2c-4134-aad0-c790040296c2","data":{"success":true,"description":null}}'
b'{"Value":400,"CookedValue":400,"Message":null,"StatusType":"Good","VarId":"f3a0a5fa-e9f7-4c33-b209-4b136241c907"}'
b'400'
b'{"Modbus-Copy1":[{"ts":1655170348381,"devicestatus":0,"values":{"outQty":400}}]}'
b'{"Modbus-Copy1":[{"ts":1655170353384,"devicestatus":0,"values":{"outQty":400}}]}'
b'{"Modbus-Copy1":[{"ts":1655170358385,"devicestatus":0,"values":{"outQty":400}}]}'
b'{"Modbus-Copy1":[{"ts":1655170363388,"devicestatus":0,"values":{"outQty":400}}]}'
b'{"Modbus-Copy1":[{"ts":1655170368390,"devicestatus":0,"values":{"outQty":400}}]}'
b'{"device":"Modbus-Copy1","id":"420f6a1f-a7e2-4dc3-840b-97fc12c3cb3c","data":{"success":true,"description":null}}'
b'{"Value":600,"CookedValue":600,"Message":null,"StatusType":"Good","VarId":"f3a0a5fa-e9f7-4c33-b209-4b136241c907"}'
b'600

**Comment by iioter** [comment]
**归档周期**是不是设置了**5000ms**?
*归档周期*与*变化上传*是配合的，如果勾选了变化上传，即使数据没变化，时间达到*归档周期*也会**强制归档**一次，如果不需要你可以把这个时间设置的更长。

**Comment by Xuquansheng** [comment]
归档周期设置为1小时：3600000ms

**Comment by iioter** [comment]
最新提交的版本
 [详见](https://github.com/iioter/iotgateway/commit/b93bbc4ab9b75e95633ba088db4fe93fa2e805ae)

**Comment by Xuquansheng** [comment]
非常感谢，能更新阿里docker镜像或者docker hub镜像吗？我用python将你的mqtt server数据发到erp系统。C#，我不熟。

**Comment by iioter** [comment]
镜像已经更新，试试看

**Comment by Xuquansheng** [comment]
新的镜像，我测过了，非常好。

**Comment by Xuquansheng** [comment]
这个问题可以关闭了。
