### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by peterli20161021** [iioter/iotgateway#2]
为 #line 指令指定的行号缺少或无效	WalkingTec.Mvvm.Mvc	D:\iotgateway-master\WalkingTec.Mvvm\WalkingTec.Mvvm.Mvc\obj\Debug\net5.0\Razor\Views\_CodeGen\Gen.cshtml.g.cs	114	活动
win10 64,.netcore 5.0 vs2019

**Comment by peterli20161021** [comment]
> 为 #line 指令指定的行号缺少或无效 WalkingTec.Mvvm.Mvc D:\iotgateway-master\WalkingTec.Mvvm\WalkingTec.Mvvm.Mvc\obj\Debug\net5.0\Razor\Views_CodeGen\Gen.cshtml.g.cs 114 活动 win10 64,.netcore 5.0 vs2019

已处理，.netcore版本是6.0已重新装5.0

**Comment by iioter** [comment]
enjoy

**Comment by iioter** [comment]
> > 为 #line 指令指定的行号缺少或无效 WalkingTec.Mvvm.Mvc D:\iotgateway-master\WalkingTec.Mvvm\WalkingTec.Mvvm.Mvc\obj\Debug\net5.0\Razor\Views_CodeGen\Gen.cshtml.g.cs 114 活动 win10 64,.netcore 5.0 vs2019
> 
> 已处理，.netcore版本是6.0已重新装5.0

thanks for your test
