### ISSUE TITLE
0.8.0版本镜像启容器报错

### ISSUE THREAD

**Issue by Xuquansheng** [iioter/iotgateway#21]
:{"Message":"Application startup exception","{OriginalFormat}":"Application startup exception"}}
iotgateway  | Unhandled exception. System.Exception: Could not resolve a service of type 'Plugin.DeviceService' for the parameter 'deviceService' of method 'Configure' on type 'IoTGateway.Startup'.

**Comment by iioter** [comment]
我发现这个问题了,很奇怪在arm上并没有这个问题

**Comment by iioter** [comment]
windows编译镜像是没问题的，已经推送你再试试，没问题关闭一下issue

**Comment by iioter** [comment]
新镜像已推送
