### ISSUE TITLE
从属设备如何通过iotgateway获取数据？？？

### ISSUE THREAD

**Issue by gyp8735abc** [iioter/iotgateway#28]
大佬，我想使用iotgateway推送数据到thingsboard，那在iotgateway中只能使用mqtt-client，但和iotgateway在一起的设备也想获取设备相关的参数值，使用[http://iotgateway.net/docs/iotgateway/mqtt 的主题没有获得消息，或者我的配置不对（文档写的不太明白），希望指点，求教了，各位大佬。

**Comment by iioter** [comment]
你好，
需求我没有完全理解，可以加QQ或者微信群详细探讨。
