### ISSUE TITLE
commit 可否规范一些

### ISSUE THREAD

**Issue by tianmaduxing** [iioter/iotgateway#30]
部分 commit “11” “22” “text” 代表什么意思？

**Comment by iioter** [comment]
不可能啊 我没有提交过这样的代码

**Comment by tianmaduxing** [comment]
![image](https://user-images.githubusercontent.com/40654776/188169382-8251a080-c58e-4899-82ad-8d7694863879.png)

**Comment by iioter** [comment]
这是社区其他贡献者的PR，还未合并。
你需要关心 [master分支的commits](https://github.com/iioter/iotgateway/commits/master)

**Comment by tianmaduxing** [comment]
好的，谢谢
