### ISSUE TITLE
实际测试没有OPC-UA

### ISSUE THREAD

**Issue by tianmaduxing** [iioter/iotgateway#31]
软件版本：0.9.4
测试步骤：编译运行
发现问题：通讯配置-->配置组--->create--->设备 ， 在这个里面找不到 OPC UA， 但是在网页里面就可以找到
![image](https://user-images.githubusercontent.com/40654776/188280259-40de9d9f-4a36-482b-be46-901f78aea7a9.png)

![image](https://user-images.githubusercontent.com/40654776/188280284-edba13df-12f5-416f-96b7-3c32f79e1290.png)

**Comment by tianmaduxing** [comment]
从v0.9.2开始默认移除了OPCUAServer，你可以手动开启；设备编辑不允许，哦，我看到了这个，自己学习一下，如何打开，感谢。

**Comment by MetSystem** [comment]
咋开的

**Comment by iioter** [comment]
![215647409c52f3d930c8a33ac267a95](https://user-images.githubusercontent.com/29589505/227866681-e47e9fcc-9e87-4cc9-a206-09f3ad4ccd01.png)
![679a1b84134926cb311faabca8d0c0d](https://user-images.githubusercontent.com/29589505/227866692-2539c77e-26cc-4f75-9356-9308f3063978.png)
![27ed3b0e6c0e6ecae82a7355f28498d](https://user-images.githubusercontent.com/29589505/227866720-f4ef8012-357c-42a5-82db-2e9affad38c7.png)
这几处取消注释 @MetSystem @tianmaduxing
