### ISSUE TITLE
源代码启动的时候报错

### ISSUE THREAD

**Issue by huangyi1214** [iioter/iotgateway#4]
源代码下载后启动调试出错，DeviceService.cs这个文件，第90行ConstructorInfo constructor = driver.Type.GetConstructor(types); 提示错误信息为：System.NullReferenceException:“Object reference not set to an instance of an object.”
另外，我想问一下这个项目是否可以建一个技术交流群，我本身也是在做智慧工厂这一块的，我也做了有几年了

**Comment by iioter** [comment]
1.先生成解决方案，再运行项目，因为是通过反射加载的驱动，你运行项目的时候还没有驱动呢
2.另外，如果是发布运行记得拷贝下面三个文件(夹)到发布目录。
drivers文件夹、
iotgateway.db文件、
Quickstarts.ReferenceServer.Config.xml文件

**Comment by iioter** [comment]
开源项目刚做2个月，还没有经历维护社区，可以加我微信 15261671110，一起交流

**Comment by iioter** [comment]
1. 先要生成解决方案，再运行项目，因为是通过反射加载的驱动，你运行项目的时候还没有驱动呢
1. 另外，如果是发布运行记得拷贝下面三个文件(夹)到发布目录。
- [ ] drivers文件夹、
- [ ] iotgateway.db文件
- [ ] Quickstarts.ReferenceServer.Config.xml文件

**Comment by iioter** [comment]
开源项目刚开始做们还没有经历维护社区。可以加我微信15261671110交流。

**Comment by jingshui127** [comment]
这个是继承了FXUA吧？？

**Comment by iioter** [comment]
> 这个是继承了FXUA吧？？

fuxa作为独立的项目部署，本项目内置mqtt、opcua服务，fuxa客户端直接订阅即可。

**Comment by jingshui127** [comment]
还以为把FUXA改为C#版本了！




恰恰用心时，恰恰无心用，无心恰恰用，用心恰恰无




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年03月22日 21:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [iioter/iotgateway] 源代码启动的时候报错 (Issue #4) |

这个是继承了FXUA吧？？

fuxa作为独立的项目部署，本项目内置mqtt、opcua服务，fuxa客户端直接订阅即可。

**Comment by iioter** [comment]
那个后端nodejs、前端ng玩不转。
我计划是先从他数据库结构入手，
然后把他的后端api改成c#的，一直没精力弄，有没有兴趣一起？

**Comment by jingshui127** [comment]
那意义就不是很大，一个大杂烩。FUXA本身就不是很稳定。出问题了，很难玩。
