### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by Duchp1997** [iioter/iotgateway#42]
目前 我启动项目的时候 发现有个driver加载不了

> info:  Plugin.DriverService[0]
      LoadDriverFiles Start
info: Plugin.DriverService[0]
      LoadDriverFiles End，Count28
info: Plugin.DriverService[0]
      LoadAllDrivers Start
fail: Plugin.DriverService[0]
      LoadAllDrivers Error E:\CShapeProject\iotgateway\IoTGateway\bin\Debug\net6.0\drivers/net6.0\CNC.Fanuc.dll
      System.IO.FileLoadException: Could not load file or assembly 'CNC.Fanuc, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
         at System.Reflection.Assembly.LoadFrom(String assemblyFile)
         at Plugin.DriverService.LoadAllDrivers() in E:\CShapeProject\iotgateway\Plugins\Plugin\DrvierService.cs:line 129
info: Plugin.DriverService[0]
      LoadAllDrivers CNC.Fanuc.H.dll OK
info: Plugin.DriverService[0]
      LoadAllDrivers CNC.MTConnect.dll OK
info: Plugin.DriverService[0]
      LoadAllDrivers Mock.TcpClient.dll OK
info: Plugin.DriverService[0]
      LoadAllDrivers OPC.DaClient.dll OK
info: Plugin.DriverService[0]
      LoadAllDrivers OPC.UaClient.dll OK
info: Plugin.DriverService[0]
      LoadAllDrivers Other.Toledo.dll OK
info: Plugin.DriverService[0]
      LoadAllDrivers PLC.AllenBradley.dll OK
info: Plugin.DriverService[0]
      LoadAllDrivers PLC.MelsecMc.dll OK
info: Plugin.DriverService[0]
      LoadAllDrivers PLC.ModBusMaster.dll OK
info: Plugin.DriverService[0]
      LoadAllDrivers PLC.OmronFins.dll OK
info: Plugin.DriverService[0]
      LoadAllDrivers PLC.SiemensS7.dll OK
info: Plugin.DriverService[0]
      LoadAllDrivers End,Count11

这里我是重新生成了解决方案，之后在vs2022的环境下运行，但是不明白为什么 在加载   `\IoTGateway\bin\Debug\net6.0\drivers\net6.0\CNC.Fanuc.dll`  的时候会出问题。

这个加载的失败会导致在调用西门子plc的时候 产生错误，没有办法获取 方法
我们后面的时候
期待得到您的回复

**Comment by iioter** [comment]
你好，
- 这个驱动是fanuc cnc的驱动。
- 这个驱动并不会影响其他驱动的设备
- 你可以重新生成解决方案

**Comment by 806072719** [comment]
问题解决了吗
