### ISSUE TITLE
bug：默认登录密码无法登录

### ISSUE THREAD

**Issue by nidbCN** [iioter/iotgateway#47]
复现步骤：构建master分支，生成解决方案后运行，输入用户名 `admin` 密码 `00000` 提示“无法登录”
![image](https://github.com/iioter/iotgateway/assets/36162655/ae66c1e0-a5d6-4683-9e77-8855b67ccda6)
![image](https://github.com/iioter/iotgateway/assets/36162655/2cf1dd14-ec65-4096-94f3-b3eef9769afb)
在 `LoginVM.cs` 调试发现密码MD5和代码中 `Utils.GetMd5String` 的返回值不同
![image](https://github.com/iioter/iotgateway/assets/36162655/e6f16731-54a7-4580-ab33-3f8c0bbbe255)
![image](https://github.com/iioter/iotgateway/assets/36162655/b3ce74b0-0f47-42b6-a078-a7cbc2177381)

**Comment by iioter** [comment]
密码：`iotgateway.net`

**Comment by nidbCN** [comment]
> 密码：`iotgateway.net`

感谢解答，顺便如果有时间可以更新下文档里面的
