### ISSUE TITLE
采集配置 -> 变量配置 页面中 "上传" 按钮未生效

### ISSUE THREAD

**Issue by 15171476828** [iioter/iotgateway#50]
复现手顺简述：
1. 本地启动项目；
2. MQTTX 连接 127.0.0.1 成功；
4. MQTTX 中 Subuscription #   也就是关注所有 MQTT 消息，能看到网关所有遥测信息；
5. 开始进入 采集配置 -> 变量配置 页面，将所有 "上传" 按钮点掉：
![image](https://github.com/user-attachments/assets/f6beb2fc-34bd-4c44-b8e9-62b893d83e6e)

期望看到的是：
    MQTTX 中 Subuscription # 对话框中停止展示所有遥测信息；

实际是：
    MQTTX 中还是能不停接收到遥测数据，证明网关还是不停的在往 MQTT Server 上塞数据；
![image](https://github.com/user-attachments/assets/650c0e6d-a481-49f7-8de4-03ef0fb42d84)

**Comment by iioter** [comment]
` internal/v1/gateway/telemetry/{DeviceName}/{VariableName}` 的消息用于前端页面获取实时值，只要状态变化或者值变化都会推送的
