### ISSUE TITLE
Any documentation about driver development? 是否有驱动开发文档？

### ISSUE THREAD

**Issue by circler3** [iioter/iotgateway#7]
Is there any plan about driver development or samples about driver development?

是否有驱动的开发文档提供？或者有样例驱动？

**Comment by iioter** [comment]
驱动只要实现: IDriver接口就可以。
方法参照
`[Method("Read方法样例", description: "Read方法样例描述")]
        public DriverReturnValueModel Read(DriverAddressIoArgModel ioarg)
        {
            DriverReturnValueModel ret = new DriverReturnValueModel
            {
                Message = "",
                StatusType = VaribaleStatusTypeEnum.Good,
                Value = $"{DeviceId} {DateTime.Now.ToString("O")} Read {ioarg.Address}"
            };
            return ret;
        }`

**Comment by circler3** [comment]
I found some details of modbus settings such as parity setting in webpage. However I cannot find any word about Even parity in the code. Can you give some instructions?

我在web界面中的通信设置内找到了校验方法设置的选项（Even等），但是我找了驱动的代码，并没有找到类似的东西，请问这个是如何实现的呢？

**Comment by iioter** [comment]
- Modbus驱动在这个目录下`iotgateway\Plugins\Drivers\DriverModbusMaster`
- 驱动使用反射方式加载
- 驱动配置参数需要加上`ConfigParameterAttribute`

**Comment by iioter** [comment]
1. 驱动简介：[驱动简介](http://iotgateway.net/docs/iotgateway/driver/drvier)
2. 驱动开发实操:[驱动开发实操](http://iotgateway.net/docs/iotgateway/driver/tcpclient)
