### ISSUE TITLE
can't be built after recent update

### ISSUE THREAD

**Issue by Eric-NZ** [iioter/iotgateway#9]
The error:

Plugins\Drivers\DriverFanuc\Fanuc.cs(12,26,12,33): error CS0535: 'Fanuc' does not implement interface member 'IDriver.connect()'

**Comment by iioter** [comment]
the latest update is work fine.
what's your code at line 68 in Fanuc.cs?it should be 'public bool Connect()' not 'public bool connect()'.

**Comment by Eric-NZ** [comment]
Yeah, it finally works. Thks.
